name: Bug Report
description: File a bug report
labels: [bug]
assignees:
  - dnunez24
body:
  - type: dropdown
    attributes:
      id: package
      label: Package
      description: Which package(s) does this bug relate to?
      multiple: true
      options:
        - audio
        - notation
        - operations
        - theory
    validations:
      required: true
  - type: textarea
    attributes:
      id: reproduction
      label: Steps to Reproduce
      description: What are the preconditions and steps to reproduce the bug?
      placeholder: |
        1. Step 1
        2. Step 2
        3. etc.
    validations:
      required: true
  - type: textarea
    attributes:
      id: expected
      label: Expected Result
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      id: actual
      label: Actual Result
      description: What actually happened?
    validations:
      required: true
  - type: input
    attributes:
      id: example
      label: Example Repo Link
      description: Link to an example repo where this issue can be reproduced
      placeholder: https://github.com/my-username/my-repo
    validations:
      required: false
  - type: textarea
    attributes:
      id: logs
      label: Logs
      description: Please copy and paste any relevant log or terminal output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
