name: Test pull requests
on:
  pull_request:
    branches:
      # Only execute this flow when PRs target the trunk
      - main
    paths:
      # Only execute this flow if source code, tests or dependencies change
      - "packages/**/*.ts"
      - "**/package*.json"
jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Upgrade to latest npm
        run: npm install --global npm
      - name: Install NPM packages
        run: npm ci
      - run: ls -Alp node_modules/@vivace
      - name: Build packages
        run: npm run build -- --verbose
      - name: Cache lint results
        uses: actions/cache@v2
        with:
          path: .eslintcache
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - name: Run lint rules
        run: npm run ci:lint
  test:
    name: Test source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch base branch
        run: |
          git fetch --no-tags --depth=1 ${{ github.base_ref }}
          git checkout -b ${{ github.base_ref }}
          git checkout ${{ github.head_ref }}
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Upgrade to latest npm
        run: npm install --global npm
      - name: Install NPM packages
        run: npm ci
      - name: Cache test results
        uses: actions/cache@v2
        with:
          path: .jestcache
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/tests/**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-
            ${{ runner.os }}-
      - name: Run tests
        run: npm run ci:test
